# Generated by Django 3.2.3 on 2022-05-14 22:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_useraccount_is_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('RegistrationNo', models.CharField(blank=True, max_length=100, null=True)),
                ('RegistrationDate', models.DateField(auto_now_add=True)),
                ('firstName', models.CharField(blank=True, max_length=100, null=True)),
                ('LastName', models.CharField(blank=True, max_length=100, null=True)),
                ('contactDept', models.CharField(blank=True, max_length=100, null=True)),
                ('contactPhone', models.CharField(blank=True, max_length=100, null=True)),
                ('sellerPhone', models.CharField(blank=True, max_length=100, null=True)),
                ('sellerEmail', models.EmailField(blank=True, max_length=200, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('companyWeb', models.CharField(blank=True, max_length=100, null=True)),
                ('streetAddress', models.CharField(blank=True, max_length=200, null=True)),
                ('seller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
